function addtext(table, type)
% Add text to vector on polar plot
    if type == "vibration"
        theta = table.PhaseAmplitude; rho = table.DoubleAmplitude;
    elseif type == "weight"
        theta  = table.PhaseWeight; rho = table.Weight;
    end
    text(deg2rad(theta), rho, ...
        [num2str(table.Weight,'%0.1f'), ...
        repmat('/', height(table), 1), ...
        num2str(table.PhaseWeight,'%-1.0f')], ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', 'FontSize', 8);
end