function addtext(table)
    %% Add text to vector on polar plot
    text(deg2rad(table.PhaseAmplitude), table.DoubleAmplitude, ...
        [num2str(table.Weight,'%0.1f'), ...
        repmat('/', height(table), 1), ...
        num2str(table.PhaseWeight,'%-1.0f')], ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', 'FontSize', 8);
end