function T = textweighttheta(T, type)
% Add text to vector on polar plot
    if type == "vibration"
        theta = T.tP2P; 
        rho = T.mP2P;
        text(deg2rad(theta), rho, ...
            [num2str(T.mWeight,'%0.1f'), ...
            repmat('/', height(T), 1), ...
            num2str(T.tWeight,'%-1.0f')], ...
            'HorizontalAlignment', 'left', ...
            'VerticalAlignment', 'bottom', 'FontSize', 8);
    elseif type == "weight"
        T = weightnumber(T);
        theta  = T.tWeight; 
        rho = T.mWeight;
        text(deg2rad(theta), rho, ...
            num2str(T.number-1,'%i'), ...
            'HorizontalAlignment', 'left', ...
            'VerticalAlignment', 'bottom', 'FontSize', 8);
    end
end